pipeline {
    agent any 

    environment {
        TOOL_DIR = "${WORKSPACE}\\ci-cd-tools"
    }

    stages {
        stage('Build') { 
            steps {
                echo 'Explore Build Stage'
                bat "${TOOL_DIR}\\build.bat ${WORKSPACE}\\Debug Debug all"
                // bat "${TOOL_DIR}\\build.bat ${WORKSPACE}\\Release Release all"
            }
        }
        stage('Static Code Analysis') {
            steps {
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
                    bat "${TOOL_DIR}\\static-analysis.bat ${WORKSPACE}\\App"
                }
            }
        }
    }
}